version: '3'
services:
  postgres:
    container_name: postgres
    image: "postgres:9.6.1"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'nestDB'
    restart: always
